### ISSUE TITLE
Waiting bug

### ISSUE THREAD

**Issue by kingboydev** [DavyCraft648/MentionSound#2]
Please fix this (im server ### **3.15.4**):
![Screenshot_۲۰۲۲-۰۷-۰۳-۲۳-۵۷-۳۹-۳۸۳_com android chrome](https://user-images.githubusercontent.com/105110200/177054550-0a33eb74-8d92-41c6-8c7f-3397a6c23428.jpg)

**Comment by Azvyl** [comment]
#1 
PM3 are no longer supported
this plugin should be used with php > 7.4
