### ISSUE TITLE
Waitning Bug {Continuation}

### ISSUE THREAD

**Issue by kingboydeve** [DavyCraft648/MentionSound#3]
You said that my version of Pocket Mine is not supported.
But ATERNOS has saved your previous version:
![Screenshot_۲۰۲۲-۰۷-۰۵-۱۲-۳۶-۴۴-۱۳۳_com android chrome](https://user-images.githubusercontent.com/101209290/177281081-466e079a-ce5f-4a5e-8704-ebc286ba79f2.jpg)

**And Please add pmmp-3.0.0 support**

**Comment by Azvyl** [comment]
Sorry, as I said in #2,
> PM3 are no longer supported

meaning, this plugin no longer provides **ANY** fix for PM3
_just blame Aternos for not using php binaries >= 7.4 to run the server_

Besides, the [website](https://poggit.pmmp.io/plugins) that Aternos used to get this plugin (poggit.pmmp.io) also doesn't accept plugin submission and update for PM3 anymore, so **ANY plugin** that has a bug in PM3 **won't have a fix** for PM3 but it is for PM4

You have to use php 8 to run PM4, so it should solve the problem
